### ISSUE TITLE
Is approval or rejection required at this stage?

### ISSUE THREAD

**Issue by weownthesky3** [KetchPartners/kmsprint2#26]
<img width= "361" alt ="comment 20" src="https://user-images.githubusercontent.com/29525920/37349469-e3b5d588-26ac-11e8-9b55-63efe6b2cc26.png">

**Comment by KetchCyork** [comment]
The plan right now and has been approved by Mark Bradford, that if the sales team is requesting a change to the estimate, they must trigger that from CPQ and we then require  a new version be created in CPM, gets internal approval (the services approval process may go in differnet directions based on the group).  Once approved it gets sent back to CPQ.  The business team needs to define approval routing by business unit
