### ISSUE TITLE
Need to track requirements and changes to requirements using Kanban boards

### ISSUE THREAD

**Issue by davebeach** [KetchPartners/kmsprint2#6]
Requirement Sources:
1.  Kanban boards - list of requirements per SharePoint (original list of requirements)
2.  New requirements identified in comments, meetings etc.
3.  Requirements resulting from issues or missing requirement.
4.  Enhancements - new requirements that are not part of the core functionality.

For Each Requirement we need:
1.  Type
2.  Who
3.  When
4.  Priority of requirement
5.  A workaround of not having a requirement
6.  Level of effort.

For Sprint 2 - what is the initial sprint 2 planned requirements to complete.

**Comment by KetchCyork** [comment]
This is frustrating because I was trying to get a clear understanding of the process for the lifecycle of teh sprint and we are still asking questions.  My though was to use todobot and segregate by status - like a kanban board, but we would need more details - here is what I created for Sprint 2 - https://ketchkmproject.workast.io/list/5a95a08132c57672fac2e27a but if you have a better idea let me know

**Comment by davebeach** [comment]
I get it.  But I’m telling you to just let me do sprint2.  Then you will get it.

Agile is not just doing waterfall within a short set period of tome.  It is throwing out planning in the traditional sense and instead focus is on doing the work in a non management way.  Study after study shows I am right on this one.  And we can even begin to see that as there has been lots of comments already (self motivated go out and figure it out - gave us the most amount of feedback we have received since I started).

Note I have already responded to every comment.

As far as slack - don’t focus on what it does now and instead tell me what are the things you want.  Then I will create a custom app to do just that.  The idea is again different.  You don’t prepackage in a standardized PMO way of doing things and instead let the participants champion that.  You use slack as a dynamic things where u create apps to automate stuff where it is needed and you don’t where it doesn’t.

At the end of each day you will get a deliverance burn rate.  You can compare that to the timeline for the sprint to get idea of where we are at.

David Beach
________________________________

**Comment by davebeach** [comment]
Let me day one then I will train you tomorrow on how to create your own app.   Then you will get that you have only seen 1% of what slack does.

David Beach
________________________________

**Comment by KetchCyork** [comment]
OK but how do I se  that?  How do we ensure that every comment that “needs” to become a requirement get created in a Kanban board (note I tried to used todobot for that) somewhere so that we create a backlog of issues to resolve.

Chris York
CEO & Principal
[Email-Signature-(Yellow-K)]

Ketch
512 Means Street
Suite 400
Atlanta, GA 30318
E:   cyork@Ketch.partners<mailto:cyork@Ketch.partners>
S:   cyork1963
P:    404-996-0238
O:   224-634-6480
M:  470-351-9194
F:    404-996-0243
W: www.Ketch.Partners<http://www.ketch.partners/>
Visit us on [Linkedin logo3] <http://www.linkedin.com/company/intenxus-llc?trk=top_nav_home>
[cid:image003.gif@01CE2F94.3B063190]<http://www.asug.com/>[cid:image004.png@01CE2F94.3B063190]<http://www.linkedin.com/in/christopherryork>

**Comment by davebeach** [comment]
You will.   Each morning with the instructions those board cards will appear.   You don’t show the entire thing the rule is you show the next tasks at hand.  It is a mistake to keep taking away now time for future what if things.

David Beach
________________________________

**Comment by KetchCyork** [comment]
What board cards? Where?  What daily meetings? What time? Who attaneds?

Chris York
CEO & Principal
[Email-Signature-(Yellow-K)]

Ketch
512 Means Street
Suite 400
Atlanta, GA 30318
E:   cyork@Ketch.partners<mailto:cyork@Ketch.partners>
S:   cyork1963
P:    404-996-0238
O:   224-634-6480
M:  470-351-9194
F:    404-996-0243
W: www.Ketch.Partners<http://www.ketch.partners/>
Visit us on [Linkedin logo3] <http://www.linkedin.com/company/intenxus-llc?trk=top_nav_home>
[cid:image003.gif@01CE2F94.3B063190]<http://www.asug.com/>[cid:image004.png@01CE2F94.3B063190]<http://www.linkedin.com/in/christopherryork>

**Comment by davebeach** [comment]
Forget the tools.  Tell me on white sheet of paper how a requirement process works. Tell me the workflows

Then I will show you how to go and create exactly that in slack.

A key. Feature. Of agile.  Is that the tools are the code that you can use to build what you need.  The manager programs the tool!!!  And adjusts as required.  I’m fact any team member is free to do this.

In modern tech world.  You just talk one thing. The workflow process to take a task from idea to delivery.

Start by telling me the attributes we need to tack onrequirement.  Also a scoring mechanism for priority.   And who needs to approve the requirement.  Then we create an app that does exactly that

Each member has a responsibility to improve their workflows.  From whatever perspective they see the world at.  This is why you get all kinds of tools in open source to do stuff like checking code for errors to auto testing and documentation.   You don’t get this by telling them here is process, now do it and report status.  That doesn’t work and this project is perfect Test case tha proves that.



David Beach
_____________________________

**Comment by KetchCyork** [comment]
OK I am starting to get it. Do you want a flow or just step by step decsription

Chris York
CEO & Principal
[Email-Signature-(Yellow-K)]

Ketch
512 Means Street
Suite 400
Atlanta, GA 30318
E:   cyork@Ketch.partners<mailto:cyork@Ketch.partners>
S:   cyork1963
P:    404-996-0238
O:   224-634-6480
M:  470-351-9194
F:    404-996-0243
W: www.Ketch.Partners<http://www.ketch.partners/>
Visit us on [Linkedin logo3] <http://www.linkedin.com/company/intenxus-llc?trk=top_nav_home>
[cid:image003.gif@01CE2F94.3B063190]<http://www.asug.com/>[cid:image004.png@01CE2F94.3B063190]<http://www.linkedin.com/in/christopherryork>

**Comment by davebeach** [comment]
No rules. Tell me what will name you comfortable   And don’t use any computer to do this.  Do it with pen and paper

David Beach
________________________________

**Comment by davebeach** [comment]
That is the point.  That is what is nice about knowing how to use an API.  You can get it to do what you want.  Rather trying to fit it into what you think.

David Beach
________________________________

**Comment by davebeach** [comment]
Set up the open source Taiga project to do the kanban boards.  you can sign up for a Taiga account, and request 

(Taiga website)[https://tree.taiga.io/project/davebeach-km-rollout/]
